parameters:
- name: packageName
  displayName: The package name to use
  type: string
  default: 

- name: package
  displayName: The package name and feature flags to build the package with (ex. ""somepackage" or "somepackage[feature1,feature2]")
  type: string
  default: 

- name: linkType
  displayName: Type of linking to use for libs in package (dynamic or static)
  type: string
  default: 

- name: buildType
  displayName: Type of build to use for libs in package (release or debug)
  type: string
  default: 

- name: publishToPipelineArtifacts
  displayName: Publish built package artifacts to pipeline artifacts
  type: boolean
  default: false

- name: publishToGitHubRelease
  displayName: Publish built package artifacts to a tagged release in the GitHub repo (A package name + version tag will be created like "somepackage-1.2.3")
  type: boolean
  default: false

- name: appendStringToGitHubRelease
  displayName: Append a string to a GitHub release (If "20240401" specified, then "somepackage-1.2.3" would become "somepackage-1.2.3--20240401")
  type: string
  default: 

- name: isPreconfiguredBuild
  displayName: isPreconfiguredBuild
  type: boolean
  default: false

- name: isCustomBuild
  displayName: isCustomBuild
  type: boolean
  default: false

stages:
- stage: Build
  displayName: 'Build'
  variables:
  - template: steps/build-vars.yml

  jobs:
  - job: Build
    condition: succeeded()  
    strategy:
      matrix:
        Windows:
          imageName: windows-2022
          osName: win
        Mac:
          imageName: macOS-12
          osName: mac
      maxParallel: 2

    pool:
      vmImage: $(imageName)

    steps:
    - template: steps/setup-auth.yml

    - template: steps/full-checkout.yml

    - powershell: |
        ./build-package.ps1 -PackageName "${{ parameters.packageName }}" -StagedArtifactsPath "$(Build.ArtifactStagingDirectory)/package"
      displayName: 'Run: install & stage (preconfigured)'
      condition: and(succeeded(), ${{ parameters.isPreconfiguredBuild }})

    - powershell: |
        ./invoke-build.ps1 -PackageAndFeatures "${{ parameters.package }}" -LinkType "${{ parameters.linkType }}" -BuildType "${{ parameters.buildType }}" -StagedArtifactsPath "$(Build.ArtifactStagingDirectory)/package"
      displayName: 'Run: install & stage (custom)'
      condition: and(succeeded(), ${{ parameters.isCustomBuild }})

    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/package
        artifactName: $(osName)
      condition: and(succeeded(), ${{ parameters.publishToPipelineArtifacts }})

    - powershell: |
        $source = "vcpkg/buildtrees/"
        $destination = "logs/"
        Write-Host "Copying files: $source ==> $destination"
        if (Test-Path $destination) {
            Remove-Item -Recurse -Force $destination
        }
        Get-ChildItem -Path $source -Recurse -Filter *.log | ForEach-Object {
          $destPath = $_.FullName -replace [regex]::Escape($source), $destination
          New-Item -ItemType Directory -Path (Split-Path $destPath) -Force -ErrorAction SilentlyContinue
          Copy-Item -Path $_.FullName -Destination $destPath
        }
        $source = "logs"
        $destination = "$(Build.ArtifactStagingDirectory)/logs"
        Write-Host "Moving files: $source ==> $destination"
        if (Test-Path $destination) {
            Remove-Item -Recurse -Force $destination
        }
        Move-Item -Path $source -Destination $destination -Force
      displayName: Stage logs for publish (if failed)
      condition: failed()

    - task: PublishBuildArtifacts@1
      displayName: Publish logs (if failed)
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/logs
        artifactName: $(osName)-logs
      condition: failed()

- stage: PublishToGitHubRelease
  displayName: 'Publish to GitHub Release'
  dependsOn: Build
  condition: and(succeeded(), ${{ parameters.publishToGitHubRelease }})

  jobs:
  - job: PublishToGitHubRelease
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: none
    
    - template: steps/setup-auth.yml

    - task: DownloadPipelineArtifact@2
      displayName: 'Download artifacts from previous stage'
      inputs:
        targetPath: $(Build.SourcesDirectory)/artifacts

    - task: PowerShell@2
      displayName: 'Prepare artifacts for staging'
      inputs:
        targetType: 'inline'
        workingDirectory: $(Build.SourcesDirectory)/artifacts
        script: |
          Move-Item -Path "./mac/*" -Destination . -Force
          Remove-Item -Path "./mac" -Recurse -Force
          Move-Item -Path "./win/*" -Destination . -Force
          Remove-Item -Path "./win" -Recurse -Force

    - task: CopyFiles@2
      displayName: 'Stage artifacts'
      inputs:
        Contents: '**'
        SourceFolder: $(Build.SourcesDirectory)/artifacts
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - task: PowerShell@2
      displayName: 'Getting info for GitHub release'
      inputs:
        targetType: 'inline'
        workingDirectory: $(Build.SourcesDirectory)/artifacts
        script: |
          $zipFiles = (Get-ChildItem -Filter "*.tar.gz")
          $gitReleaseNotes = "| File | Hash |"
          $gitReleaseNotes += "`n| ---------- | ---------- |"
          foreach ($zipFile in $zipFiles) {
             $hash = (Get-FileHash -Algorithm MD5 -Path $zipFile.FullName).Hash.ToLower()
             $gitReleaseNotes += "`n| $($zipFile.Name) | $hash |"
          }
          function Escape-Data {
            param(
              [string]$data
            )
            $data = $data -replace '%', '%AZP25'
            $data = $data -replace [System.Environment]::NewLine, '%0A'
            $data = $data -replace "`r", '%0D'
            return $data
          }
          $gitReleaseNotes = Escape-Data $gitReleaseNotes
          $packageInfoJsonFile = "package.json"
          $artifactsUnzippedDir = "artifactContents"
          $artifactZip = (Get-ChildItem -Filter "*.tar.gz" | Select-Object -First 1).Name
          New-Item -ItemType Directory -Name "$artifactsUnzippedDir"
          tar -xzvf $artifactZip -C $artifactsUnzippedDir
          Push-Location $artifactsUnzippedDir
          $gitReleaseTagName = ""
          $gitReleaseTagSuffix = "${{ parameters.appendStringToGitHubRelease }}".Trim()
          if (Test-Path -Path $packageInfoJsonFile -PathType Leaf) {
              $jsonContent = Get-Content -Path $packageInfoJsonFile -Raw | ConvertFrom-Json
              $version = $jsonContent.version
              $packageName = $jsonContent.packageName
              $gitReleaseTagName = "$packageName-$version"
          }
          Pop-Location
          if( $gitReleaseTagSuffix -ne "") {
             $gitReleaseTagName += "--$gitReleaseTagSuffix"
          }
          Write-Host "##vso[task.setvariable variable=gitReleaseTagName]$gitReleaseTagName"
          Write-Host "##vso[task.setvariable variable=gitReleaseNotes]$gitReleaseNotes"

    - task: GitHubRelease@1
      displayName: 'Create GitHub release'
      inputs:
        gitHubConnection: 'TechSmithGitHub'
        repositoryName: '$(Build.Repository.Name)'
        target: '$(Build.SourceVersion)'
        action: 'create'
        title: $(gitReleaseTagName)
        tagSource: 'userSpecifiedTag'
        tag: $(gitReleaseTagName)
        releaseNotesSource: 'inline'
        releaseNotesInline: |
          $(gitReleaseNotes)
        addChangeLog: false
        isDraft: false
        isPreRelease: false
        assets: |
          $(Build.ArtifactStagingDirectory)/*
      condition: and(succeeded(), ${{ parameters.publishToGitHubRelease }})
