# Build script for Soundpipe on Windows
# Called at build time (not configure time) via ExternalProject_Add_Step or vcpkg

if(NOT SOUNDPIPE_SOURCE_DIR)
   message(FATAL_ERROR "SOUNDPIPE_SOURCE_DIR not set")
endif()

# Normalize the path and remove any quotes
string(REPLACE "\"" "" SOUNDPIPE_SOURCE_DIR "${SOUNDPIPE_SOURCE_DIR}")
file(TO_CMAKE_PATH "${SOUNDPIPE_SOURCE_DIR}" SP_ROOT)

# Verify the source directory exists
if(NOT EXISTS "${SP_ROOT}")
   message(FATAL_ERROR "Soundpipe source directory does not exist: ${SP_ROOT}")
endif()

# Find the C compiler if not specified
if(NOT CMAKE_C_COMPILER OR CMAKE_C_COMPILER STREQUAL "cl.exe")
   find_program(CMAKE_C_COMPILER_FOUND NAMES cl.exe)
   if(CMAKE_C_COMPILER_FOUND)
      set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER_FOUND}")
      message(STATUS "Soundpipe: Found cl.exe at ${CMAKE_C_COMPILER}")
   else()
      set(CMAKE_C_COMPILER "cl.exe")
      message(STATUS "Soundpipe: Using cl.exe from PATH")
   endif()
endif()

# Find the archiver if not specified  
if(NOT CMAKE_AR OR CMAKE_AR STREQUAL "lib.exe")
   find_program(CMAKE_AR_FOUND NAMES lib.exe)
   if(CMAKE_AR_FOUND)
      set(CMAKE_AR "${CMAKE_AR_FOUND}")
      message(STATUS "Soundpipe: Found lib.exe at ${CMAKE_AR}")
   else()
      set(CMAKE_AR "lib.exe")
      message(STATUS "Soundpipe: Using lib.exe from PATH")
   endif()
endif()

# Define all modules from config.def.mk
# We hardcode this list instead of parsing config.mk since that file
# is generated by the Makefile system which doesn't run on Windows
set(ALL_MODULES
    base
    ftbl
    tevent
    adsr
    allpass
    atone
    autowah
    bal
    bar
    biquad
    biscale
    blsaw
    blsquare
    bltriangle
    fold
    bitcrush
    brown
    butbp
    butbr
    buthp
    butlp
    clip
    clock
    comb
    compressor
    count
    conv
    crossfade
    dcblock
    delay
    diode
    dist
    dmetro
    drip
    dtrig
    dust
    eqfil
    expon
    fof
    fog
    fofilt
    foo
    fosc
    gbuzz
    hilbert
    in
    incr
    jcrev
    jitter
    line
    lpf18
    maygate
    metro
    mincer
    mode
    moogladder
    noise
    nsmp
    osc
    oscmorph
    pan2
    panst
    pareq
    paulstretch
    pdhalf
    peaklim
    phaser
    phasor
    pinknoise
    pitchamdf
    pluck
    port
    posc3
    progress
    prop
    pshift
    ptrack
    randh
    randi
    randmt
    random
    reverse
    reson
    revsc
    rms
    rpt
    rspline
    saturator
    samphold
    scale
    scrambler
    sdelay
    slice
    smoothdelay
    spa
    sparec
    streson
    switch
    tabread
    tadsr
    talkbox
    tblrec
    tbvcf
    tdiv
    tenv
    tenv2
    tenvx
    tgate
    thresh
    timer
    tin
    tone
    trand
    tseg
    tseq
    vdelay
    voc
    vocoder
    waveset
    wpkorg35
    zitarev
    fftwrapper
    padsynth
)

# Remove modules that require libsndfile (diskin, wavout, wavin)
# and lpc (requires x86 assembly)
list(
   REMOVE_ITEM
   ALL_MODULES
   "diskin"
   "wavout"
   "wavin"
   "lpc"
)

# Generate soundpipe.h by concatenating all module headers
message(STATUS "Generating soundpipe.h...")
set(SOUNDPIPE_H_PATH "${SP_ROOT}/h/soundpipe.h")

# Start with header guard
file(WRITE "${SOUNDPIPE_H_PATH}" "#ifndef SOUNDPIPE_H\n")
file(APPEND "${SOUNDPIPE_H_PATH}" "#define SOUNDPIPE_H\n")

# Concatenate all module headers
foreach(MODULE ${ALL_MODULES})
   set(MODULE_HEADER "${SP_ROOT}/h/${MODULE}.h")
   if(EXISTS "${MODULE_HEADER}")
      file(READ "${MODULE_HEADER}" MODULE_HEADER_CONTENT)
      file(APPEND "${SOUNDPIPE_H_PATH}" "${MODULE_HEADER_CONTENT}")
   else()
      message(WARNING "Header not found: ${MODULE_HEADER}")
   endif()
endforeach()

# Close header guard
file(APPEND "${SOUNDPIPE_H_PATH}" "#endif\n")

message(STATUS "Generated soundpipe.h at ${SOUNDPIPE_H_PATH}")

# Build list of source files
set(MODULE_SOURCES "")
set(MODULE_OBJECTS "")
foreach(MODULE ${ALL_MODULES})
   if(NOT
      MODULE
      STREQUAL
      ""
   )
      list(APPEND MODULE_SOURCES "${SP_ROOT}/modules/${MODULE}.c")
      list(APPEND MODULE_OBJECTS "${SP_ROOT}/modules/${MODULE}.obj")
   endif()
endforeach()

# Manually add library sources (from the included Makefiles)
set(LIB_SOURCES
    "${SP_ROOT}/lib/inih/ini.c"
    "${SP_ROOT}/lib/fft/fftlib.c"
    "${SP_ROOT}/lib/kissfft/kiss_fft.c"
    "${SP_ROOT}/lib/kissfft/kiss_fftr.c"
    "${SP_ROOT}/lib/spa/spa.c"
    "${SP_ROOT}/lib/dr_wav/dr_wav.c"
)

set(LIB_OBJECTS
    "${SP_ROOT}/lib/inih/ini.obj"
    "${SP_ROOT}/lib/fft/fftlib.obj"
    "${SP_ROOT}/lib/kissfft/kiss_fft.obj"
    "${SP_ROOT}/lib/kissfft/kiss_fftr.obj"
    "${SP_ROOT}/lib/spa/spa.obj"
    "${SP_ROOT}/lib/dr_wav/dr_wav.obj"
)

# Note: Clang-cl handles forward slashes fine, so we don't convert include paths to native format
# to avoid command-line parsing issues

# Try to find clang-cl (ships with Visual Studio 2019+) which supports C99 properly
# For VS path like: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe
# clang-cl is at: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/Llvm/x64/bin/clang-cl.exe
message(STATUS "Soundpipe: Detecting compiler for Windows build...")
message(STATUS "  CMAKE_C_COMPILER: ${CMAKE_C_COMPILER}")

get_filename_component(MSVC_BIN_DIR "${CMAKE_C_COMPILER}" DIRECTORY)
get_filename_component(TARGET_ARCH "${MSVC_BIN_DIR}" NAME)
get_filename_component(MSVC_HOSTARCH_DIR "${MSVC_BIN_DIR}" DIRECTORY)
get_filename_component(MSVC_BIN_ROOT "${MSVC_HOSTARCH_DIR}" DIRECTORY)
get_filename_component(MSVC_VERSION_DIR "${MSVC_BIN_ROOT}" DIRECTORY)
# MSVC_VERSION_DIR is now: .../VC/Tools/MSVC/14.44.35207
# We need to go up 2 levels to get to VC
get_filename_component(MSVC_TOOLS_DIR "${MSVC_VERSION_DIR}" DIRECTORY)
# MSVC_TOOLS_DIR is now: .../VC/Tools/MSVC
get_filename_component(VC_TOOLS_DIR "${MSVC_TOOLS_DIR}" DIRECTORY)
# VC_TOOLS_DIR is now: .../VC/Tools
get_filename_component(VC_DIR "${VC_TOOLS_DIR}" DIRECTORY)
# VC_DIR is now: .../VC

message(STATUS "  Target architecture: ${TARGET_ARCH}")
message(STATUS "  VC directory: ${VC_DIR}")

# Check if CLANG_CL_HINT was provided (from portfile)
if(CLANG_CL_HINT AND EXISTS "${CLANG_CL_HINT}")
   set(CLANG_CL_PATH "${CLANG_CL_HINT}")
   message(STATUS "  ✓ Using clang-cl from hint: ${CLANG_CL_PATH}")
else()
   # Try VS 2022/2019 structure: VC/Tools/Llvm/<arch>/bin/clang-cl.exe
   set(CLANG_CL_PATH "${VC_DIR}/Tools/Llvm/${TARGET_ARCH}/bin/clang-cl.exe")
   message(STATUS "  Checking for clang-cl at: ${CLANG_CL_PATH}")
endif()

if(NOT EXISTS "${CLANG_CL_PATH}")
   set(CLANG_CL_PATH "${VC_DIR}/Tools/Llvm/bin/clang-cl.exe")
   message(STATUS "  Checking for clang-cl at: ${CLANG_CL_PATH}")
endif()

# Fallback: try same directory as cl.exe
if(NOT EXISTS "${CLANG_CL_PATH}")
   set(CLANG_CL_PATH "${MSVC_BIN_DIR}/clang-cl.exe")
   message(STATUS "  Checking for clang-cl at: ${CLANG_CL_PATH}")
endif()

# Fallback: search for clang-cl in PATH or common installation locations
if(NOT EXISTS "${CLANG_CL_PATH}")
   message(STATUS "  Searching for clang-cl in system PATH and common locations...")
   find_program(CLANG_CL_FOUND clang-cl)
   if(CLANG_CL_FOUND)
      set(CLANG_CL_PATH "${CLANG_CL_FOUND}")
      message(STATUS "  Found clang-cl at: ${CLANG_CL_PATH}")
   endif()
   unset(CLANG_CL_FOUND CACHE)
endif()

if(EXISTS "${CLANG_CL_PATH}")
   message(STATUS "  ✓ Found clang-cl at: ${CLANG_CL_PATH}")
   message(STATUS "  Using clang-cl for C99 compatibility")
   set(C_COMPILER "${CLANG_CL_PATH}")
   set(COMPILE_FLAGS
       /nologo
       /W3
       /O2
       -Wno-everything
       /DSP_VERSION=1.7.0
       /DNO_LIBSNDFILE
       /I${SP_ROOT}/h
       /I${SP_ROOT}/lib/inih
       /I${SP_ROOT}/lib/faust
       /I${SP_ROOT}/lib/fft
       /I${SP_ROOT}/lib/kissfft
       /I${SP_ROOT}/lib/spa
       /I${SP_ROOT}/lib/openlpc
       /I${SP_ROOT}/lib/dr_wav
   )
else()
   message(STATUS "  ✗ clang-cl not found")
   message(STATUS "  Using MSVC cl.exe with C++ mode (/TP) and compatibility wrapper")
   message(STATUS "  Compiler: ${CMAKE_C_COMPILER}")
   set(C_COMPILER "${CMAKE_C_COMPILER}")

   # Create a compatibility header that wraps malloc/calloc/realloc for C++ compilation
   set(CPP_COMPAT_H "${SP_ROOT}/h/cpp_malloc_compat.h")
   file(WRITE "${CPP_COMPAT_H}" "/* C++ malloc compatibility wrapper for MSVC */\n")
   file(APPEND "${CPP_COMPAT_H}" "#ifndef CPP_MALLOC_COMPAT_H\n")
   file(APPEND "${CPP_COMPAT_H}" "#define CPP_MALLOC_COMPAT_H\n")
   file(APPEND "${CPP_COMPAT_H}" "#ifdef __cplusplus\n")
   file(APPEND "${CPP_COMPAT_H}" "#include <stdlib.h>\n")
   file(APPEND "${CPP_COMPAT_H}" "#include <string.h>\n")
   file(APPEND "${CPP_COMPAT_H}" "inline void* cpp_malloc(size_t size) { return malloc(size); }\n")
   file(APPEND "${CPP_COMPAT_H}"
        "inline void* cpp_calloc(size_t num, size_t size) { return calloc(num, size); }\n"
   )
   file(APPEND "${CPP_COMPAT_H}"
        "inline void* cpp_realloc(void* ptr, size_t size) { return realloc(ptr, size); }\n"
   )
   file(APPEND "${CPP_COMPAT_H}" "#define malloc(size) cpp_malloc(size)\n")
   file(APPEND "${CPP_COMPAT_H}" "#define calloc(num, size) cpp_calloc(num, size)\n")
   file(APPEND "${CPP_COMPAT_H}" "#define realloc(ptr, size) cpp_realloc(ptr, size)\n")
   file(APPEND "${CPP_COMPAT_H}" "#endif\n")
   file(APPEND "${CPP_COMPAT_H}" "#endif\n")

   # Compile as C++ to support void pointer arithmetic
   # Convert paths to native format for MSVC
   file(TO_NATIVE_PATH "${SP_ROOT}/h/cpp_malloc_compat.h" CPP_COMPAT_H_NATIVE)
   
   set(COMPILE_FLAGS
       /TP
       /nologo
       /W0
       /O2
       /std:c++14
       /DSP_VERSION=1.7.0
       /DNO_LIBSNDFILE
       "/FI${CPP_COMPAT_H_NATIVE}"
       /I${SP_ROOT}/h
       /I${SP_ROOT}/lib/inih
       /I${SP_ROOT}/lib/faust
       /I${SP_ROOT}/lib/fft
       /I${SP_ROOT}/lib/kissfft
       /I${SP_ROOT}/lib/spa
       /I${SP_ROOT}/lib/openlpc
       /I${SP_ROOT}/lib/dr_wav
   )
endif()

# Compile module source files
message(STATUS "Compiling Soundpipe module sources...")
foreach(SRC_FILE IN LISTS MODULE_SOURCES)
   get_filename_component(OBJ_NAME "${SRC_FILE}" NAME_WE)
   set(OBJ_FILE "${SP_ROOT}/modules/${OBJ_NAME}.obj")

   file(TO_NATIVE_PATH "${SRC_FILE}" SRC_FILE_NATIVE)
   file(TO_NATIVE_PATH "${OBJ_FILE}" OBJ_FILE_NATIVE)

   execute_process(
      COMMAND ${C_COMPILER} ${COMPILE_FLAGS} ${SRC_FILE_NATIVE} /Fo${OBJ_FILE_NATIVE} /c
      WORKING_DIRECTORY "${SP_ROOT}"
      RESULT_VARIABLE COMPILE_RESULT
      OUTPUT_VARIABLE COMPILE_OUTPUT
      ERROR_VARIABLE COMPILE_ERROR
   )

   if(NOT
      COMPILE_RESULT
      EQUAL
      0
   )
      message(FATAL_ERROR "Failed to compile ${SRC_FILE}:\n${COMPILE_OUTPUT}\n${COMPILE_ERROR}")
   endif()
endforeach()

# Compile library source files
message(STATUS "Compiling Soundpipe library sources...")
foreach(SRC_FILE IN LISTS LIB_SOURCES)
   get_filename_component(OBJ_NAME "${SRC_FILE}" NAME_WE)
   get_filename_component(SRC_DIR "${SRC_FILE}" DIRECTORY)
   set(OBJ_FILE "${SRC_DIR}/${OBJ_NAME}.obj")

   file(TO_NATIVE_PATH "${SRC_FILE}" SRC_FILE_NATIVE)
   file(TO_NATIVE_PATH "${OBJ_FILE}" OBJ_FILE_NATIVE)

   execute_process(
      COMMAND ${C_COMPILER} ${COMPILE_FLAGS} ${SRC_FILE_NATIVE} /Fo${OBJ_FILE_NATIVE} /c
      WORKING_DIRECTORY "${SP_ROOT}"
      RESULT_VARIABLE COMPILE_RESULT
      OUTPUT_VARIABLE COMPILE_OUTPUT
      ERROR_VARIABLE COMPILE_ERROR
   )

   if(NOT
      COMPILE_RESULT
      EQUAL
      0
   )
      message(FATAL_ERROR "Failed to compile ${SRC_FILE}:\n${COMPILE_OUTPUT}\n${COMPILE_ERROR}")
   endif()
endforeach()

# Create static library using lib.exe (MSVC librarian)
message(STATUS "Creating Soundpipe static library...")
set(ALL_OBJECTS ${MODULE_OBJECTS} ${LIB_OBJECTS})
execute_process(
   COMMAND ${CMAKE_AR} /nologo /OUT:${SP_ROOT}/soundpipe.lib ${ALL_OBJECTS}
   WORKING_DIRECTORY "${SP_ROOT}"
   RESULT_VARIABLE LIB_RESULT
   OUTPUT_VARIABLE LIB_OUTPUT
   ERROR_VARIABLE LIB_ERROR
)

if(NOT
   LIB_RESULT
   EQUAL
   0
)
   message(FATAL_ERROR "Failed to create library:\n${LIB_OUTPUT}\n${LIB_ERROR}")
endif()

message(STATUS "Successfully built ${SP_ROOT}/soundpipe.lib")
