parameters:
- name: packageName
  type: string
- name: isPreconfiguredBuild
  type: boolean
- name: requiresGithubToken
  type: string

steps:
- pwsh: |
    ./build-package.ps1 -PackageName "${{ parameters.packageName }}" -StagedArtifactsPath "$(Build.ArtifactStagingDirectory)/package" -TargetPlatform $(osName)
  displayName: 'Run: install & stage (preconfigured)'
  condition: and(succeeded(), ${{ parameters.isPreconfiguredBuild }}, eq(variables['requiresGithubToken'], '${{ parameters.requiresGithubToken }}'))
  ${{ if eq(parameters.requiresGithubToken, 'true') }}:
    env:
      GithubToken: $(GithubToken)
      VCPKG_KEEP_ENV_VARS: GithubToken
