pr: none

trigger: none

parameters:

- name: package
  displayName: Package to install, plus any optional feature flags (ex. "somepackage" or "somepackage[feature1,feature2]")
  type: string

- name: linkType
  displayName: Link Type
  type: string
  default: dynamic
  values:
  - dynamic
  - static

- name: buildType
  displayName: Build Type
  type: string
  default: release
  values:
  - release
  - debug

stages:
- template: templates/build.yml
  parameters:
    package: ${{ parameters.package }}
    linkType: ${{ parameters.linkType }}
    buildType: ${{ parameters.buildType }}
    publishToPipelineArtifacts: true
    publishToGitHubRelease: false
    isCustomBuild: true
