pr: none

trigger: none

parameters:

- name: package
  displayName: Package to install, plus any optional feature flags (ex. "somepackage" or "somepackage[feature1,feature2]")
  type: string

- name: linkType
  displayName: Link Type
  type: string
  default: dynamic
  values:
  - dynamic
  - static

- name: buildType
  displayName: Build Type
  type: string
  default: release
  values:
  - release
  - debug

- name: publishToGitHubRelease
  displayName: Publish built package artifacts to a tagged release in the GitHub repo (A package name + version tag will be created like "somepackage-1.2.3")
  type: boolean
  default: false

stages:
- template: templates/build.yml
  parameters:
    package: ${{ parameters.package }}
    linkType: ${{ parameters.linkType }}
    buildType: ${{ parameters.buildType }}
    publishToPipelineArtifacts: true
    publishToGitHubRelease: ${{ parameters.publishToGitHubRelease }}
    isCustomBuild: true
